name: U6 BOT

on:
  schedule:
    - cron: "1 */6 * * *"  # Toutes les 6 heures
  workflow_dispatch:       # Permet de déclencher manuellement ce workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        npm update
        npm install discord.js
        npm install dotenv
        npm install puppeteer
        sudo apt update
        sudo apt install libavcodec-extra
        sudo add-apt-repository --remove ppa:jonathonf/ffmpeg-4
        sudo apt-get update
        sudo apt-get install ffmpeg
        sudo snap install ffmpeg
        sudo add-apt-repository ppa:mc3man/trusty-media
        sudo apt update
        sudo apt install ffmpeg
        ffmpeg -version
        

    - name: Run Discord Bot (with 30 minute timeout)
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        PREFIX: ${{ secrets.PREFIX }}
      run: |
        node index.js
